### ISSUE TITLE
Breaking change introduced in 1.2.7 - window is not defined

### ISSUE THREAD

**Issue by jenwei** [html5crew/ua_parser#11]
Noticed that a new version of ua_parser (`1.2.7`) was released ~21h ago, and I'm running into a `window is not defined` error

Here's the line identified in the my stacktrace: `ua_parser/src/js/ua_parser.js:112:35checkOs`

Seems like the latest version should've been a major version bump as it involves a breaking change?

**Comment by eastkiki** [comment]
@jenwei 

Thank you for your report. A bug has been fixed in v1.2.8.
