### ISSUE TITLE
Doesn't recognize IE

### ISSUE THREAD

**Issue by Spetnik** [html5crew/ua_parser#6]
I've been trying with the following UA strings (from my IIS logs) and browser is always unknown and OS version is always 0:
- `Mozilla/4.0+(compatible;+MSIE+8.0;+Windows+NT+6.1;+Trident/4.0;+SLCC2;+.NET+CLR+2.0.50727;+.NET+CLR+3.5.30729;+.NET+CLR+3.0.30729;+Media+Center+PC+6.0;+InfoPath.3;+.NET4.0C)`
- `Mozilla/4.0+(compatible;+MSIE+7.0;+Windows+NT+6.1;+WOW64;+Trident/4.0;+SLCC2;+.NET+CLR+2.0.50727;+.NET+CLR+3.5.30729;+.NET+CLR+3.0.30729;+Media+Center+PC+6.0)`
- `Mozilla/5.0+(compatible;+MSIE+9.0;+Windows+NT+6.1;+Trident/5.0)`
- `Mozilla/5.0+(compatible;+MSIE+10.0;+Windows+NT+6.1;+Trident/6.0)`

Sample result:
```
{ ua: 'mozilla/5.0+(compatible;+msie+10.0;+windows+nt+6.1;+trident/6.0)',
  browser:
   { unknown: true,
     name: 'unknown',
     version: { info: '0.0.0', major: '0', minor: '0', patch: '0' } },
  platform: '',
  os:
   { windows: true,
     name: 'windows',
     version: { info: '0.0.0', major: '0', minor: '0', patch: '0' } },
  app: { isApp: false } }
```

**Comment by eastkiki** [comment]
@Spetnik 

The UA-string of the browser is usually as follows.

```
mozilla/5.0 (compatible; msie 10.0; windows nt 6.1; trident/6.0)
```

It seems that your server stores UA-string in the log by replacing spaces with +.
Replace + with a space before parsing UA-string.
